### ISSUE TITLE
JSONPath support is broken

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#132]
According to http://jsonpath.com/ with given JSON `{"myNode":{"inner":"foo"}}` and JSONPath `$.myNode.inner` the result is `[ "foo" ]`

But 
```
final String json = "{\"myNode\":{\"inner\":\"foo\"}}";
assertThatJson(json).inPath("$.myNode.inner").isArray();
```
throws:
```
java.lang.IllegalArgumentException: Can not parse actual value., took 1.612 sec
[error]     at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.readValue(Jackson2NodeFactory.java:59)
[error]     at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.readValue(AbstractNodeFactory.java:53)
[error]     at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.convertToNode(AbstractNodeFactory.java:31)
[error]     at net.javacrumbs.jsonunit.core.internal.Converter.convertToNode(Converter.java:123)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:50)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:37)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.getNode(JsonUtils.java:89)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.nodeAbsent(JsonUtils.java:134)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.nodeAbsent(JsonUtils.java:105)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.nodeAbsent(JsonUtils.java:101)
[error]     at net.javacrumbs.jsonunit.assertj.JsonAssert.isPresent(JsonAssert.java:189)
[error]     at net.javacrumbs.jsonunit.assertj.JsonAssert.assertType(JsonAssert.java:180)
[error]     at net.javacrumbs.jsonunit.assertj.JsonAssert.isArray(JsonAssert.java:109)
```

**Comment by lukas-krecan** [comment]
It is not always an array for example 

` String json = "{\"myNode\":{\"inner\":\"foo\"}}";        assertThatJson(json).inPath("$.myNode.inner").isString().isEqualTo("foo");`

**Comment by lukas-krecan** [comment]
Fixed in 2.0.0.RC2

**Comment by eximius313** [comment]
> It is not always an array for example
> 
> `String json = "{\"myNode\":{\"inner\":\"foo\"}}"; assertThatJson(json).inPath("$.myNode.inner").isString().isEqualTo("foo");`

Are you sure?
In my example: 
```
final String json = "{\"foo\":{\"bar\":{\"baz\":[{\"id\":\"hello\",\"value\":\"world\"}]}}}";
```
This pass: 
```
assertThatJson(json).inPath("$.foo.bar.baz[?(@.id==\"hello\")].value").isArray().containsExactly("world"));
```
But this fails:
```
assertThatJson(json).inPath("$.foo.bar.baz[?(@.id==\"hello\")].value).isString().isEqualTo("world"));
``` 
with:
```
Node "$.foo.bar.baz[?(@.id=="hello")].value" has invalid type, expected: <string> but was: <[world]>
```

**Comment by lukas-krecan** [comment]
https://github.com/json-path/JsonPath#what-is-returned-when

**Comment by eximius313** [comment]
Ok, thanks for explanation. Maybe its worth to link that in Javadoc

**Comment by eximius313** [comment]
> It is not always an array for example
>
>` String json = "{\"myNode\":{\"inner\":\"foo\"}}"; assertThatJson(json).inPath("$.myNode.inner").isString().isEqualTo("foo");`

@lukas-krecan -> it ocurrs that you can always return an array!
```java
Configuration conf = Configuration.defaultConfiguration().addOptions(Option.ALWAYS_RETURN_LIST);
String json = "{\"myNode\":{\"inner\":\"foo\"}}";

List<String> values = JsonPath.using(conf).parse(json).read("$.myNode.inner");
System.out.println(values);
```
consistency for the win! ;)
