### ISSUE TITLE
[BUG] inPath is not supporting OR

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#164]
Having such JSON:
```
{
    "foo1": {
        "test":"bar",
        "value": "x"
    },
    "foo2": {
        "test":"baz",
        "value": "y"
    }
}
```
and such query: `$[?(@.test=="bar"|@.test=="baz")].value`
http://jsonpath.com/ shows as a result:
```
[
  "x",
  "y"
]
```
which is correct, but JsonUnit throws:
```
failed: com.jayway.jsonpath.InvalidPathException: Expected character: ), took 11.35 sec
[error]     at com.jayway.jsonpath.internal.CharacterIndex.readSignificantChar(CharacterIndex.java:218)
[error]     at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalANDOperand(FilterCompiler.java:185)
[error]     at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalAND(FilterCompiler.java:151)
[error]     at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalOR(FilterCompiler.java:131)
[error]     at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:77)
[error]     at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:53)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readFilterToken(PathCompiler.java:461)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:141)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readPropertyOrFunctionToken(PathCompiler.java:237)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:151)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readDotToken(PathCompiler.java:171)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:145)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58)
[error]     at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75)
[error]     at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101)
[error]     at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467)
[error]     at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:87)
[error]     at com.jayway.jsonpath.JsonPath.read(JsonPath.java:488)
[error]     at net.javacrumbs.jsonunit.jsonpath.JsonPathAdapter.inPath(JsonPathAdapter.java:39)
[error]     at net.javacrumbs.jsonunit.assertj.JsonAssert$ConfigurableJsonAssert.inPath(JsonAssert.java:302)
```

**Comment by eximius313** [comment]
Moreover, `$[?(@.test)].value` should return:
```
[
  "x",
  "y"
]
```
but it returns `[]` instead

**Comment by lukas-krecan** [comment]
Hi, JsonUnit delegates JsonPath work to https://github.com/json-path/JsonPath so if you feel that you queries should work, please file your ticket in https://github.com/json-path/JsonPath/issues

**Comment by eximius313** [comment]
Ok, I filled the issues. Let's wait

**Comment by lukas-krecan** [comment]
https://github.com/json-path/JsonPath/issues/525
