### ISSUE TITLE
[BUG] inPath regression

### ISSUE THREAD

**Issue by eximius313** [lukas-krecan/JsonUnit#166]
this previously worked:
```
assertThatJson(json).inPath("<some path>")
      .isArray()
      .containsExactlyInAnyOrder(
          Json.toJson(dto1),
          Json.toJson(dto2)
      );
```
now it throws:
```
failed: java.lang.IllegalArgumentException: Unsupported type class com.fasterxml.jackson.databind.node.ObjectNode, took 0.878 sec
[error]     at net.javacrumbs.jsonunit.core.internal.GenericNodeBuilder.newNode(GenericNodeBuilder.java:64)
[error]     at net.javacrumbs.jsonunit.core.internal.GenericNodeBuilder.wrapDeserializedObject(GenericNodeBuilder.java:29)
[error]     at net.javacrumbs.jsonunit.core.internal.JsonUtils.wrapDeserializedObject(JsonUtils.java:183)
[error]     at net.javacrumbs.jsonunit.assertj.JsonComparator.compare(JsonComparator.java:51)
[error]     at org.assertj.core.internal.ComparatorBasedComparisonStrategy.iterablesRemoveFirst(ComparatorBasedComparisonStrategy.java:111)
[error]     at org.assertj.core.internal.Iterables.iterablesRemoveFirst(Iterables.java:271)
[error]     at org.assertj.core.internal.Iterables.assertContainsExactlyInAnyOrder(Iterables.java:1173)
[error]     at org.assertj.core.api.AbstractIterableAssert.containsExactlyInAnyOrder(AbstractIterableAssert.java:284)
[error]     at org.assertj.core.api.ListAssert.containsExactlyInAnyOrder(ListAssert.java:277)
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback.The behavior had to change in order to fix #162. This should work

```
assertThatJson(json).inPath("<some path>")
      .isArray()
      .containsExactlyInAnyOrder(
          JsonAssertions.json(dto1),
          JsonAssertions.json(dto2)
      );

```

Explanation: The trouble is in AssertJ array comparison. JsonUnit provides a comparator that is able to compare two JSON values but AssertJ assumes that comparison is symmetric so it passes the expected/actual argument pair in (almost) random order. Json comparison is not symmetric, actual value is already parsed, expected value usually needs to be parsed or at least converted to an internal format. By using json/value methods from JsonAssertions you mark the value as expected value and JsonUnit knows what to do with it.

**Comment by eximius313** [comment]
It does not work an will not work unless you use exatcly the same parser with exactly the same settings as production code.

**Comment by eximius313** [comment]
Ok, this little monster works:
```
assertThatJson(json).inPath("<some path>")
      .isArray()
      .containsExactlyInAnyOrder(
          JsonAssertions.json(Json.toJson(dto1)),
          JsonAssertions.json(Json.toJson(dto2))
      );
```
but it's so wrong...
