### ISSUE TITLE
org/assertj/core/api/StringAssert is not assignable to org/assertj/core/api/AbstractStringAssert

### ISSUE THREAD

**Issue by raul-casallas** [lukas-krecan/JsonUnit#313]
**Groovy issue with json-unit-assertj**

I'm trying to run the basic samples of json-unit-assertj using groovy (under Katalon), this is the sample script:

```
@Grab(group='net.javacrumbs.json-unit', module='json-unit-assertj', version='2.22.0')
import static net.javacrumbs.jsonunit.assertj.JsonAssertions.assertThatJson;
import static net.javacrumbs.jsonunit.assertj.JsonAssertions.json;

// compares two JSON documents (note lenient parsing of expected value)
assertThatJson("{\"a\":1, \"b\":2}").isEqualTo("{b:2, a:1}");

// AssertJ map assertions (numbers are converted to BigDecimals)
assertThatJson("{\"a\":1}").isObject().containsEntry("a", BigDecimal.valueOf(1));
```

but I get the following error:

```
================================================

12-29-2020 01:25:09 PM Test Cases/New Test Case

Elapsed time: 2.079s

Test Cases/New Test Case FAILED.
Reason:
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    net/javacrumbs/jsonunit/assertj/JsonAssert.asString()Lorg/assertj/core/api/AbstractStringAssert; @4: areturn
  Reason:
    Type 'org/assertj/core/api/StringAssert' (current frame, stack[0]) is not assignable to 'org/assertj/core/api/AbstractStringAssert' (from method signature)
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'net/javacrumbs/jsonunit/assertj/JsonAssert' }
    stack: { 'org/assertj/core/api/StringAssert' }
  Bytecode:
    0x0000000: 2ab6 0137 b0                           

	at net.javacrumbs.jsonunit.assertj.JsonAssertions.assertThatJson(JsonAssertions.java:38)
	at net.javacrumbs.jsonunit.assertj.JsonAssertions$assertThatJson.callStatic(Unknown Source)
	at New Test Case.run(New Test Case:27)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:394)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:385)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:364)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:356)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:251)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1609266307878.run(TempTestCase1609266307878.groovy:25)

```

I understand that is some kind of incompatibility between **json-unit-assertj** and **assertj-core**, so I did some attempts to recompile and generate new jars, but that doesn't work for me, the workaround was downgrade to **2.8.0** and at least for now is working like a charm.

**Comment by lukas-krecan** [comment]
Hi, thanks for reporting it. What version of AssertJ did you try to use and what version of JsonUnit?

**Comment by raul-casallas** [comment]
In this test, I'm using **json-unit-assertj** vertsion **2.22.0** and that (I believe) that resolves to **assertj-core** 3.18.1.

**Comment by raul-casallas** [comment]
wait, I need to check if this has to do with the groovy compiler version that is embedded into katalon studio because I just try directly calling the script, and it works. Sorry... I'll keep you posted

**Comment by lukas-krecan** [comment]
I can imagine some conflicts between versions, but the library is tested well with assertj-core 3.18.1
