### ISSUE TITLE
Incompatibility with assert-j to 3.20

### ISSUE THREAD

**Issue by carlmolemans** [lukas-krecan/JsonUnit#379]
Some methods were made final which are overwritten in json-unit-assertj. 
Eg. AbstractMapAssert.contains(Entry) is now final in assertj. 

Example stack: 
ava.lang.VerifyError: class net.javacrumbs.jsonunit.assertj.JsonMapAssert overrides final method contains.([Ljava/util/Map$Entry;)Lorg/assertj/core/api/AbstractMapAssert;

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.javacrumbs.jsonunit.assertj.JsonAssert.isObject(JsonAssert.java:131)

**Comment by lukas-krecan** [comment]
Thank you for reporting will fix it one way or the other.

**Comment by lukas-krecan** [comment]
https://github.com/lukas-krecan/JsonUnit/runs/2835150405?check_suite_focus=true

**Comment by lukas-krecan** [comment]
Released as 2.27.0
