### ISSUE TITLE
NoSuchMethodError at GsonNodeFactory.readValue

### ISSUE THREAD

**Issue by siralam2104** [lukas-krecan/JsonUnit#394]
**Describe the bug**

My usage:

```kotlin
            assertThatJson(someJsonString).isEqualTo("""{ "some": "long json string" }""")
```

Expected behaviour: can run successfully can give assertion result

Observed behaviour: Throw the below exception

```
java.lang.NoSuchMethodError: 'com.google.gson.JsonElement com.google.gson.JsonParser.parseReader(java.io.Reader)'

	at net.javacrumbs.jsonunit.core.internal.GsonNodeFactory.readValue(GsonNodeFactory.java:60)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.readValue(AbstractNodeFactory.java:83)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.convertToNode(AbstractNodeFactory.java:38)
	at net.javacrumbs.jsonunit.core.internal.Converter.convertToNode(Converter.java:128)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:60)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:45)
	at net.javacrumbs.jsonunit.assertj.JsonAssert.<init>(JsonAssert.java:69)
	at net.javacrumbs.jsonunit.assertj.JsonAssert$ConfigurableJsonAssert.<init>(JsonAssert.java:281)
	at net.javacrumbs.jsonunit.assertj.JsonAssert$ConfigurableJsonAssert.<init>(JsonAssert.java:286)
	at net.javacrumbs.jsonunit.assertj.JsonAssertions.assertThatJson(JsonAssertions.java:38)
	at net.javacrumbs.jsonunit.assertj.JsonAssertions.assertThatJson(JsonAssertions.java:53)
```

I am not using `Gson` in my project but `Moshi`, I also tried adding the below to the class of my test

```
    @Before
    open fun setupJsonUnit() {
        System.setProperty("json-unit.libraries", "moshi")
    }
```

But the result is the same, may be I do `setProperty` in the wrong place?

**Comment by lukas-krecan** [comment]
Hi, it seems you have old version of Gson in the classpath. The easiest way is to debug the code and see why it decided to go the Gson path.

**Comment by siralam2104** [comment]
But I am not using Gson in my project at all, and I also tried to include explicitly the latest Gson dependency, it still throws the same exception.

By debug do you mean looking at the stacktrace of your lib?

**Comment by lukas-krecan** [comment]
Easiest way is to add breakpoint here https://github.com/lukas-krecan/JsonUnit/blob/master/json-unit-core/src/main/java/net/javacrumbs/jsonunit/core/internal/Converter.java#L126 or line 75 and see what's going on there

**Comment by lukas-krecan** [comment]
By guess is that you should set the system property in static init block, @ Before might be called to late.

**Comment by siralam2104** [comment]
> My guess is that you should set the system property in static init block, @ Before might be called too late.
This is it. Thank you!
