### ISSUE TITLE
Can not parse actual value when asserting first element of array

### ISSUE THREAD

**Issue by mitasov-ra** [lukas-krecan/JsonUnit#496]
**Describe the bug**
1. AssertJ, 2.33.0
2. Create a small reproducible example
   ```kotlin
   assertThatJson("""["abc"]""")
       .isArray()
       .first()
       .isEqualTo(value("abc"))
   ```
            
4. Describe expected behavior
   Test is expected to pass. But I get
   ```
   Can not parse actual value: 'abc'
   java.lang.IllegalArgumentException: Can not parse actual value: 'abc'
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.newParseException(AbstractNodeFactory.java:71)
	at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.readValue(Jackson2NodeFactory.java:59)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.readValue(AbstractNodeFactory.java:83)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.convertToNode(AbstractNodeFactory.java:38)
	at net.javacrumbs.jsonunit.core.internal.Converter.convertToNode(Converter.java:128)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:60)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:45)
	at net.javacrumbs.jsonunit.assertj.JsonAssert.<init>(JsonAssert.java:68)
	at net.javacrumbs.jsonunit.assertj.JsonListAssert.lambda$new$0(JsonListAssert.java:38)
	at org.assertj.core.api.FactoryBasedNavigableListAssert.toAssert(FactoryBasedNavigableListAssert.java:43)
	at org.assertj.core.api.AbstractIterableAssert.internalFirst(AbstractIterableAssert.java:3273)
	at org.assertj.core.api.AbstractIterableAssert.first(AbstractIterableAssert.java:3236)
   ```

**Comment by mitasov-ra** [comment]
@lukas-krecan FYI

**Comment by lukas-krecan** [comment]
Sorry, the bug fell between the cracks. This is strange, as Java text block needs to have a newline after `"""` This passes to me

```
assertThatJson("""
                            ["abc"]
            """)
                .isArray()
                .first()
                .isEqualTo(value("abc"));
```
