### ISSUE TITLE
custom matcher for embedded json

### ISSUE THREAD

**Issue by akanksham1** [lukas-krecan/JsonUnit#71]
I am facing issue while passing jsonObject as parameter . It is considering it as a whole string and not as a argument as can be checked in attached screenshot .
![actual vs expected](https://user-images.githubusercontent.com/30916551/29200955-5fb328b8-7e77-11e7-939c-0b3edebe8260.PNG)

String expected = "{\"response\":{\'${json-unit.matches:containsJSON}\'"+jsonObject+"}}"; //Not working 
        assertJsonEquals(expected, actual, JsonAssert.withMatcher("containsJSON", embeddedJsonMatcher));

Check this 
![json_matcher](https://user-images.githubusercontent.com/30916551/29200700-06c192d2-7e75-11e7-8e2b-d3933b72ff2e.PNG)

**Comment by akanksham1** [comment]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting a colon to separate field name and value
 at [Source: java.io.StringReader@bb310d52; line: 1, column: 50]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon2(ReaderBasedJsonParser.java:1773)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipColon(ReaderBasedJsonParser.java:1746)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:621)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:210)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:218)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1819)
	at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.readValue(Jackson2NodeFactory.java:57)

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback, if I understand your code correctly, easier way to do the comparison would have been:

    assertJsonPartEquals(expectedJsonString, actual, "response");

If it does not work, please provide the example in text form so I do not have to copy it from the screenshot by hand.

**Comment by akanksham1** [comment]
[EmbeddedJsonMatcher.txt](https://github.com/lukas-krecan/JsonUnit/files/1240761/EmbeddedJsonMatcher.txt)

Please find attached code file .

**Comment by akanksham1** [comment]
[EmbeddedJsonMatcher.txt](https://github.com/lukas-krecan/JsonUnit/files/1240789/EmbeddedJsonMatcher.txt)
Please find attached File ..

**Comment by lukas-krecan** [comment]
The reason is that your 'expected' value is not a valid JSON.
`{"response":{'${json-unit.matches:containsJSON}'{"empolyees":{"firstName":"Kate","lastName":"Smith"},"attributes":null}}}`
