### ISSUE TITLE
Facing issues when comparing jsons with Arrays

### ISSUE THREAD

**Issue by princejt** [lukas-krecan/JsonUnit#72]
java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
	at net.javacrumbs.jsonunit.core.internal.JsonOrgNodeFactory$JSONArrayNode.arrayElements(JsonOrgNodeFactory.java:188)
	at net.javacrumbs.jsonunit.core.internal.Diff.compareArrayNodes(Diff.java:317)
	at net.javacrumbs.jsonunit.core.internal.Diff.compareNodes(Diff.java:229)
	at net.javacrumbs.jsonunit.core.internal.Diff.compareObjectNodes(Diff.java:120)
	at net.javacrumbs.jsonunit.core.internal.Diff.compareNodes(Diff.java:226)
	at net.javacrumbs.jsonunit.core.internal.Diff.compare(Diff.java:82)
	at net.javacrumbs.jsonunit.core.internal.Diff.similar(Diff.java:454)
	at net.javacrumbs.jsonunit.JsonAssert.assertJsonPartEquals(JsonAssert.java:80)
	at net.javacrumbs.jsonunit.JsonAssert.assertJsonEquals(JsonAssert.java:65)
	at net.javacrumbs.jsonunit.JsonAssert.assertJsonEquals(JsonAssert.java:58)

Is there a particular json jar dependecy?  The one I am using doesnt have iterator method

**Comment by lukas-krecan** [comment]
Hi, it seems you are using old version of org.json package. See this issue for more details https://github.com/lukas-krecan/JsonUnit/issues/56

**Comment by princejt** [comment]
i was using below dependency.

<dependency>
  <groupId>org.json</groupId>
  <artifactId>json</artifactId>
  <version>20140107</version>
</dependency>

The issue got fixed by using below dependency.

<dependency>
  <groupId>org.json</groupId>
  <artifactId>json</artifactId>
  <version>20170516</version>
</dependency>
