### ISSUE TITLE
Custom Matchers Does Not Work With Json Array

### ISSUE THREAD

**Issue by paulwinters** [lukas-krecan/JsonUnit#76]
I am trying to use the custom matcher feature with a JSON array but JsonUnit throws a parsing exception.

Test Case

``` 
@Test
    public void customMatchersArray() {
        final String actualJson = "{\"array\": [1,2,3]}";
        final String expectJson = "{\"array\":${json-unit.matches:notEmpty}\"}";

        assertJsonEquals(expectJson, actualJson, JsonAssert.withMatcher("notEmpty", Matchers.not(Matchers.emptyArray())));
    }
```

Output

```
FAILED: customMatchersArray
java.lang.IllegalArgumentException: Can not parse expected value.
	at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.readValue(Jackson2NodeFactory.java:59)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.readValue(AbstractNodeFactory.java:44)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.convertToNode(AbstractNodeFactory.java:31)
	at net.javacrumbs.jsonunit.core.internal.Converter.convertToNode(Converter.java:123)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:60)
	at net.javacrumbs.jsonunit.core.internal.Diff.create(Diff.java:79)
	at net.javacrumbs.jsonunit.JsonAssert.assertJsonPartEquals(JsonAssert.java:80)
	at net.javacrumbs.jsonunit.JsonAssert.assertJsonEquals(JsonAssert.java:66)
```

**Comment by lukas-krecan** [comment]
Hi, thanks for feedback. expectJson has to be a  valid JSON, you are missing \" before  ${json-unit.matches:notEmpty}
