### ISSUE TITLE
JsonUnit 4.0.0: causes java.lang.ClassNotFoundException: org.springframework.beans.factory.BeanFactoryInitializer

### ISSUE THREAD

**Issue by pstorch** [lukas-krecan/JsonUnit#855]
**Describe the bug**
1. Describe which variant of the API are you using (AssertJ, Hamcrest, ...)
AssertJ, SpringMVC
2. Create a small reproducible example and paste it the bug report.
tbd. (Need some time to create this)
3. Describe expected behavior

Until json-unit 3.5.0 all tests did run fine, since 4.0.0 I get the following Exception in my Spring Tests:

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/factory/BeanFactoryInitializer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.springframework.test.context.support.DynamicPropertiesContextCustomizer.customizeContext(DynamicPropertiesContextCustomizer.java:70)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextCustomizerAdapter.initialize(SpringBootContextLoader.java:443)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:627)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:401)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	... 28 more

```

Using Spring Boot 3.3.5.

**Comment by jpgoelz** [comment]
I can confirm this for Spring Boot 2.7.18.

**Comment by lukas-krecan** [comment]
JsonUnit is dependent on Spring 6.2 so maybe it's pulling a newer version of a Spring module. It should not happen if you are using Spring Boot BOM. Can you check the Spring versions resolved by your build tool?

**Comment by lukas-krecan** [comment]
Btw. JsonUnit should work with older version of Spring, so you can force older version

**Comment by jpgoelz** [comment]
> JsonUnit is dependent on Spring 6.2 so maybe it's pulling a newer version of a Spring module. It should not happen if you are using Spring Boot BOM. Can you check the Spring versions resolved by your build tool?

This is what we have.
![image](https://github.com/user-attachments/assets/ed9fbc0a-8fba-43ee-94ef-1ee2c1a7ee28)

The resolved Spring core version is 5.3.31 if that is what you were asking.

**Comment by lukas-krecan** [comment]
What's you spring-test version?

**Comment by pstorch** [comment]
This is when 3.5.0 is used:
![Screenshot 2024-11-20 at 07 56 32](https://github.com/user-attachments/assets/6fe7f6d8-76ea-4247-8788-28b0960351f1)

And this is with 4.0.0:

![Screenshot 2024-11-20 at 07 57 42](https://github.com/user-attachments/assets/9e391afe-fa33-4ad1-8620-79dcce00056e)

**Comment by lukas-krecan** [comment]
Yes, JsonUnit pulled in a newer version of spring-test. In this case you have to explicitly set the same version as the rest of spring dependencies in your Maven or Gradle file (or use Spring Boot BOM that does it for you)

**Comment by pstorch** [comment]
@lukas-krecan thanks

I already use the spring Boot BOM:

```
dependencies {
    implementation(platform(SpringBootPlugin.BOM_COORDINATES))
...
```

But I had to explicitly exclude the `spring-test` dependency from json-unit:

```
    testImplementation(libs.json.unit.spring) {
        // https://github.com/lukas-krecan/JsonUnit/issues/855
        exclude(group = "org.springframework", module = "spring-test")
    }
```

This solved it for me.

**Comment by jpgoelz** [comment]
For us, spring-test is at 5.3.31:

![image](https://github.com/user-attachments/assets/915abf2c-7bf1-465b-ab2e-cafd41990d00)

But also, we are not using json-unit-spring but json-unit-assertj.

![image](https://github.com/user-attachments/assets/6f17d32e-b248-4631-a8ba-a6ae05fe93d4)

**Comment by lukas-krecan** [comment]
@jpgoelz Hi, can you please share what exception are you seeing? Is it really the same as the one reported [here](https://github.com/lukas-krecan/JsonUnit/issues/855#issue-2672138667)?

**Comment by jpgoelz** [comment]
> @jpgoelz Hi, can you please share what exception are you seeing? Is it really the same as the one reported [here](https://github.com/lukas-krecan/JsonUnit/issues/855#issue-2672138667)?

Sorry, of course it is not. 🙈 It is a `java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/cfg/DatatypeFeature` exception:

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/cfg/DatatypeFeature

	at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.getMapperProvider(Jackson2NodeFactory.java:76)
	at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.getMapper(Jackson2NodeFactory.java:67)
	at net.javacrumbs.jsonunit.core.internal.Jackson2NodeFactory.readValue(Jackson2NodeFactory.java:58)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.readValue(AbstractNodeFactory.java:72)
	at net.javacrumbs.jsonunit.core.internal.AbstractNodeFactory.convertToNode(AbstractNodeFactory.java:37)
	at net.javacrumbs.jsonunit.core.internal.Converter.convertToNode(Converter.java:110)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:54)
	at net.javacrumbs.jsonunit.core.internal.JsonUtils.convertToJson(JsonUtils.java:44)
	at net.javacrumbs.jsonunit.assertj.JsonAssert.<init>(JsonAssert.java:70)
	at net.javacrumbs.jsonunit.assertj.JsonAssert.<init>(JsonAssert.java:79)
	at net.javacrumbs.jsonunit.assertj.JsonAssert$ConfigurableJsonAssert.<init>(JsonAssert.java:315)
	at net.javacrumbs.jsonunit.assertj.JsonAssert$ConfigurableJsonAssert.<init>(JsonAssert.java:320)
	at net.javacrumbs.jsonunit.assertj.JsonAssertions.assertThatJson(JsonAssertions.java:50)
``` 

If you wish, I can open a new issue.

**Comment by lukas-krecan** [comment]
Too late for that. It's another version incompatibility. Can you share the version of jackson-databind package?

**Comment by jpgoelz** [comment]
Sure, jackson-databind has version 2.13.5.

**Comment by lukas-krecan** [comment]
You have to upgrade Jackson to at least 2.14

**Comment by pstorch** [comment]
We got the Spring Boot 3.4.0 update today. Now my fix from https://github.com/lukas-krecan/JsonUnit/issues/855#issuecomment-2488003220 is not needed anymore.

From my point of view this ticket can be closed.

**Comment by jpgoelz** [comment]
> You have to upgrade Jackson to at least 2.14

With 2.14 it would not work (because there seems to be an issue with the JSR310, which is not a JsonUnit issue), but it worked with 2.15.

With this, my issue is resolved as well. Thanks!

**Comment by lukas-krecan** [comment]
Let's keep it open for a while, so others have an easier time finding it. Thanks
